"""
네이버 맞춤법 검사기 passportKey 추출 → data/naver-speller-key.js 저장
GitHub Actions에서 매일 실행하여 키를 갱신한다.
"""
import re
import urllib.request
import os
import json
from datetime import datetime, timezone, timedelta

SEARCH_URL = (
    "https://search.naver.com/search.naver"
    "?query=%EB%A7%9E%EC%B6%A4%EB%B2%95+%EA%B2%80%EC%82%AC%EA%B8%B0"
)
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "naver-speller-key.js")


def fetch_passport_key():
    req = urllib.request.Request(SEARCH_URL, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=15) as res:
        html = res.read().decode("utf-8", errors="replace")
    m = re.search(r"passportKey=([a-f0-9]+)", html)
    if not m:
        raise RuntimeError("passportKey not found in Naver search page")
    return m.group(1)


def main():
    try:
        key = fetch_passport_key()
    except Exception as e:
        print(f"[naver-key] 키 추출 실패: {e} — 기존 파일 유지")
        return  # 실패 시 기존 키 파일 유지, 파이프라인 중단하지 않음

    kst = datetime.now(timezone(timedelta(hours=9)))
    data = {
        "passportKey": key,
        "updatedAt": kst.strftime("%Y-%m-%d %H:%M KST"),
    }
    js = f"// Auto-generated by fetch_naver_key.py\nwindow._NAVER_SPELLER = {json.dumps(data, ensure_ascii=False)};\n"
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"[naver-key] passportKey={key[:8]}... saved ({kst.strftime('%Y-%m-%d %H:%M')})")


if __name__ == "__main__":
    main()
